services:
  playwright:
    image: node:18.20.5-bookworm-slim
    build: .
    volumes:
      - ./:/iot-app-kit
    ports:
      - 9323:9323/tcp
      - 6007:6007/tcp
    working_dir: '/iot-app-kit'
    command: sh -c "npm ci --prefer-offline --no-audit --progress=false --workspaces --include-workspace-root && npx playwright install --with-deps && npx turbo test:ui:ci --filter=@iot-app-kit/react-components"
