export const CONFIG_PANEL_OPEN_WIDTH_PIXELS = 500;
export const CONFIG_PANEL_COLLAPSED_WIDTH_PIXELS = 80;
export const CONFIG_PANEL_BORDER_WIDTH = 2;
export const PROPERTY_PANEL_DRAG_HANDLE_ICON_SIZE = 20;
export const PROPERTY_PANEL_COLLAPSED_HEIGHT_PIXELS = 70;
export const PROPERTY_PANEL_DEFAULT_HEIGHT_PIXELS = 299;
