/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { DataStreamQuery } from "./data-module";
import { MinimalLiveViewport } from "@synchro-charts/core";
export namespace Components {
    interface IotKpi {
        "isEditing": boolean | undefined;
        "query": DataStreamQuery;
        "viewport": MinimalLiveViewport | undefined;
        "widgetId": string;
    }
    interface IotTestRoutes {
    }
    interface TestingGround {
    }
}
declare global {
    interface HTMLIotKpiElement extends Components.IotKpi, HTMLStencilElement {
    }
    var HTMLIotKpiElement: {
        prototype: HTMLIotKpiElement;
        new (): HTMLIotKpiElement;
    };
    interface HTMLIotTestRoutesElement extends Components.IotTestRoutes, HTMLStencilElement {
    }
    var HTMLIotTestRoutesElement: {
        prototype: HTMLIotTestRoutesElement;
        new (): HTMLIotTestRoutesElement;
    };
    interface HTMLTestingGroundElement extends Components.TestingGround, HTMLStencilElement {
    }
    var HTMLTestingGroundElement: {
        prototype: HTMLTestingGroundElement;
        new (): HTMLTestingGroundElement;
    };
    interface HTMLElementTagNameMap {
        "iot-kpi": HTMLIotKpiElement;
        "iot-test-routes": HTMLIotTestRoutesElement;
        "testing-ground": HTMLTestingGroundElement;
    }
}
declare namespace LocalJSX {
    interface IotKpi {
        "isEditing"?: boolean | undefined;
        "query"?: DataStreamQuery;
        "viewport"?: MinimalLiveViewport | undefined;
        "widgetId"?: string;
    }
    interface IotTestRoutes {
    }
    interface TestingGround {
    }
    interface IntrinsicElements {
        "iot-kpi": IotKpi;
        "iot-test-routes": IotTestRoutes;
        "testing-ground": TestingGround;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "iot-kpi": LocalJSX.IotKpi & JSXBase.HTMLAttributes<HTMLIotKpiElement>;
            "iot-test-routes": LocalJSX.IotTestRoutes & JSXBase.HTMLAttributes<HTMLIotTestRoutesElement>;
            "testing-ground": LocalJSX.TestingGround & JSXBase.HTMLAttributes<HTMLTestingGroundElement>;
        }
    }
}
