import {
  SITEWISE_ASSET_SYNC_WORKSPACE,
  AFRICA_SITE_WORKSPACE,
  ANTARCTICA_SITE_WORKSPACE,
  ASIA_SITE_WORKSPACE,
  AUSTRALIA_SITE_WORKSPACE,
  EUROPE_SITE_WORKSPACE,
  NORTH_AMERICA_SITE_WORKSPACE,
  SOUTH_AMERICA_SITE_WORKSPACE,
} from './workspaceSummaries';

export const WORKSPACE_SUMMARIES = [
  SITEWISE_ASSET_SYNC_WORKSPACE,
  AFRICA_SITE_WORKSPACE,
  ANTARCTICA_SITE_WORKSPACE,
  ASIA_SITE_WORKSPACE,
  AUSTRALIA_SITE_WORKSPACE,
  EUROPE_SITE_WORKSPACE,
  NORTH_AMERICA_SITE_WORKSPACE,
  SOUTH_AMERICA_SITE_WORKSPACE,
];
