module.exports = {
  colorBackgroundContainerContent: 'colorBackgroundContainerContent',
  colorBackgroundContainerHeader: 'colorBackgroundContainerHeader',
  colorBackgroundDropdownItemDefault: 'colorBackgroundDropdownItemDefault',
  colorBackgroundDropdownItemHover: 'colorBackgroundDropdownItemHover',
  colorBackgroundInputDefault: 'colorBackgroundInputDefault',
  colorBackgroundInputDisabled: 'colorBackgroundInputDisabled',
  colorBackgroundItemSelected: 'colorBackgroundItemSelected',
  colorBackgroundLayoutMain: 'colorBackgroundLayoutMain',
  colorBackgroundNotificationBlue: 'colorBackgroundNotificationBlue',
  colorBackgroundNotificationGreen: 'colorBackgroundNotificationGreen',
  colorBackgroundNotificationRed: 'colorBackgroundNotificationRed',
  colorBorderButtonNormalDefault: 'colorBorderButtonNormalDefault',
  colorBorderContainerTop: 'colorBorderContainerTop',
  colorBorderDividerDefault: 'colorBorderDividerDefault',
  colorChartsYellow700: 'colorChartsYellow700',
  colorForegroundControlDefault: 'colorForegroundControlDefault',
  colorTextBodySecondar: 'colorTextBodySecondary',
  colorTextFormSecondary: 'colorTextFormSecondary',
  colorTextHeadingDefault: 'colorTextHeadingDefault',
  colorTextInputPlaceholder: 'colorTextInputPlaceholder',
  colorTextLabel: 'colorTextLabel',
  colorTextNotificationDefault: 'colorTextNotificationDefault',
}
