import { COMPARISON_OPERATOR } from '@synchro-charts/core';

export const DEFAULT_THRESHOLD_COLOR = '#D0021B';
export const OPS_ALLOWED_WITH_STRING: COMPARISON_OPERATOR[] = [COMPARISON_OPERATOR.EQUAL, COMPARISON_OPERATOR.CONTAINS];
