export const SVG_STROKE_SOLID = '1,0';
export const SVG_STROKE_DASHED = '10,5';
export const SVG_STROKE_DOTTED = '3,3';

export const WIDGET_INITIAL_HEIGHT = 400;
export const WIDGET_INITIAL_WIDTH = 650;

export const GAUGE_WIDGET_INITIAL_HEIGHT = 400;
export const GAUGE_WIDGET_INITIAL_WIDTH = 500;

export const KPI_WIDGET_INITIAL_HEIGHT = 200;
export const KPI_WIDGET_INITIAL_WIDTH = 350;

export const TABLE_WIDGET_INITIAL_HEIGHT = 300;
export const TABLE_WIDGET_INITIAL_WIDTH = 850;

export const TABLE_WIDGET_MAX_HEIGHT = 520;
export const TABLE_OVERFLOW_HEIGHT = 200;

export const STATUS_WIDGET_INITIAL_HEIGHT = 200;
export const STATUS_WIDGET_INITIAL_WIDTH = 350;

export const TEXT_WIDGET_INITIAL_HEIGHT = 100;
export const TEXT_WIDGET_INITIAL_WIDTH = 200;
