export enum SceneCapabilities {
  MATTERPORT = 'MATTERPORT',
  DYNAMIC_SCENE = 'DYNAMIC_SCENE',
}

export enum SceneMetadataMapKeys {
  MATTERPORT_SECRET_ARN = 'MATTERPORT_SECRET_ARN',
  SCENE_ROOT_ENTITY_ID = 'SCENE_ROOT_ENTITY_ID',
}
