export const CONFIG_PANEL_OPEN_WIDTH = 500;
export const CONFIG_PANEL_COLLAPSE_WIDTH = 80;
export const CONFIG_PANEL_BORDER_WIDTH = 2;
export const DRAWER_DRAG_HANDLE_ICON_SIZE = 20;
export const DRAWER_COLLAPSED_HEIGHT = 70;
export const DRAWER_DEFAULT_HEIGHT = 500;
