name: Publish Storybook
on:
  pull_request:
    paths:
    - 'packages/scene-composer/**'
jobs:
  publish-storybook:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: 'true'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'

      - name: Install and Build
        run: |
          npm ci
          npm run build
          npm run build-storybook -w packages/scene-composer

      # store storybook site
      - name: Upload Storybook Assets
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: scene-composer-${{ github.sha }}
          path: packages/scene-composer/storybook-static

