on:
  push:
    branches:
      - main
    paths:
    - 'packages/**'
    - '.github/workflows/*'
name: Create release PR
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          command: manifest-pr
          prerelease: true
          release-as: 3.0.1-alpha
          token: ${{secrets.GITHUB_TOKEN}}
          default-branch: main

  update-pull-request:
    name: Update pull request
    runs-on: ubuntu-latest
    needs: release-please
    if: ${{ !needs.release-please.outputs.releases_created }}
    steps:
      - name: Fetching the repository
        uses: actions/checkout@v3
        with:
          ref: release-please--branches--main
          fetch-depth: 2

      - name: Setting up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Updating package-lock.json file
        run: npm install --no-audit --no-fund --ignore-scripts --package-lock-only

      - name: Merging changes with last commit
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit --amend --no-edit

      - name: Push changes
        uses: ad-m/github-push-action@master
        continue-on-error: true
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: release-please--branches--main
          force: true
