name: E2E Tests
on: [pull_request]
jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - uses: actions/setup-node@v3
        with:
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Determine if tests need to be ran
        run: npx turbo-ignore components --task=test:integration

      - name: Run integration tests
        uses: cypress-io/github-action@v5
        with:
          command: npx turbo run test:integration --filter=[HEAD~1]
      # after the test run completes
      # store videos and any screenshots
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-screenshots
          path: packages/components/cypress/screenshots
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-videos
          path: packages/components/cypress/videos
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-snapshots
          path: packages/components/cypress/snapshots
