name: 'Dashboard UI Tests'
on: [pull_request]
jobs:
  test-runner:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Install and Build
        run: |
          npm ci
          npm run build

      - name: Install Playwright
        working-directory: ./packages/dashboard
        run: npx playwright install --with-deps

      - name: Build Storybook
        working-directory: ./packages/dashboard
        run: npm run build-storybook --quiet

      - name: Run tests
        working-directory: ./packages/dashboard
        run: npm run test:ui
