export const mockData = [
  {
    arn: 'arn',
    assetTemplateId: '123',
    creationDate: 'string',
    description: 'blah blah',
    id: 'abc',
    lastUpdateDate: 'string',
    name: 'Asset without child references',
    assetProperties: [
      {
        id: 'e46a96c9-1062-4740-880d-1ef2b7b09cb2',
        name: 'Nominal Power',
        alias: null,
        dataType: null,
        unit: null,
        value: 10,
      },
      {
        id: '20f360d7-3fed-417b-8132-e6f5804239ac',
        name: 'Efficiency (%)',
        alias: null,
        dataType: null,
        unit: null,
        value: 0,
      },
      {
        id: '5e80bad5-d752-4012-91aa-ade07c648679',
        name: 'Location',
        alias: null,
        dataType: null,
        unit: null,
        value: 1.0,
      },
      {
        id: 'f848b397-d30b-4154-9efb-84f5cffd8b11',
        name: 'Efficiency',
        alias: null,
        dataType: null,
        unit: null,
        value: 10,
      },
      {
        id: '671b4ddc-2123-4c67-95a5-d31f8d7e2696',
        name: 'Power',
        alias: null,
        dataType: null,
        unit: null,
        value: '[10,20]',
      },
    ],
    references: [],
    status: {
      state: 'ACTIVE',
    },
  },
  {
    arn: 'arn',
    assetTemplateId: '123',
    creationDate: 'string',
    description: 'blah blah',
    id: 'abc',
    lastUpdateDate: 'string',
    name: 'Asset with References',
    assetProperties: [
      {
        id: 'e46a96c9-1062-4740-880d-1ef2b7b09cb2',
        name: 'Nominal Power',
        alias: null,
        dataType: null,
        unit: null,
        value: 10,
      },
    ],
    references: [{ id: 'abc1', name: 'ref name', size: 1, type: { name: 'type name', templateId: 'template id' } }],
    status: {
      state: 'ACTIVE',
    },
  },
];

export const mockNonActiveData = [
  {
    arn: 'arn',
    assetTemplateId: '123',
    creationDate: 'string',
    description: 'blah blah',
    id: 'abc',
    lastUpdateDate: 'string',
    name: 'Asset without child references',
    assetProperties: [
      {
        id: 'e46a96c9-1062-4740-880d-1ef2b7b09cb2',
        name: 'Nominal Power',
        alias: null,
        dataType: null,
        unit: null,
        value: 10,
      },
      {
        id: '20f360d7-3fed-417b-8132-e6f5804239ac',
        name: 'Efficiency (%)',
        alias: null,
        dataType: null,
        unit: null,
        value: 0,
      },
      {
        id: '5e80bad5-d752-4012-91aa-ade07c648679',
        name: 'Location',
        alias: null,
        dataType: null,
        unit: null,
        value: 1.0,
      },
      {
        id: 'f848b397-d30b-4154-9efb-84f5cffd8b11',
        name: 'Efficiency',
        alias: null,
        dataType: null,
        unit: null,
        value: 10,
      },
      {
        id: '671b4ddc-2123-4c67-95a5-d31f8d7e2696',
        name: 'Power',
        alias: null,
        dataType: null,
        unit: null,
        value: '[10,20]',
      },
    ],
    references: [],
    assetStatus: {
      state: 'CREATING',
    },
  },
  {
    arn: 'arn',
    assetTemplateId: '123',
    creationDate: 'string',
    description: 'blah blah',
    id: 'abc',
    lastUpdateDate: 'string',
    name: 'Asset with References',
    assetProperties: [
      {
        id: 'e46a96c9-1062-4740-880d-1ef2b7b09cb2',
        name: 'Nominal Power',
        alias: null,
        dataType: null,
        unit: null,
        value: 10,
      },
    ],
    references: [{ id: 'abc1', name: 'ref name', size: 1, type: { name: 'type name', templateId: 'template id' } }],
    status: {
      state: 'FAILED',
    },
  },
];
